const team = (name, code, flag) => ({ name, code, flag })

const lineup = (prefix) =>
  [
    ['1', 'Goalkeeper'],
    ['4', 'Defender'],
    ['8', 'Midfielder'],
    ['10', 'Forward'],
  ].map(([shirtNumber, position]) => ({
    id: `${prefix}-${shirtNumber}`,
    name: `${prefix} ${position}`,
    position,
    shirtNumber,
  }))

export const mockMatches = [
  {
    id: 'mock-final-mex-rsa',
    round: 'Matchday 1',
    date: '2026-06-11',
    time: '12:00 PM PDT',
    kickoffAt: '2026-06-11T19:00:00Z',
    group: 'Group A',
    ground: 'Estadio Azteca',
    minute: null,
    status: 'Final',
    home: team('Mexico', 'MEX', '🇲🇽'),
    away: team('South Africa', 'RSA', '🇿🇦'),
    score: { home: 2, away: 1 },
    details: {
      homeFormation: '4-2-3-1',
      awayFormation: '4-4-2',
      homeLineup: lineup('Mexico'),
      awayLineup: lineup('South Africa'),
      homeBench: [{ id: 'mex-b1', name: 'Mexico Substitute', position: 'Forward', shirtNumber: 19 }],
      awayBench: [{ id: 'rsa-b1', name: 'South Africa Substitute', position: 'Midfielder', shirtNumber: 16 }],
      homeStatistics: { ball_possession: 58, shots: 12, shots_on_goal: 6, corner_kicks: 5, fouls: 10 },
      awayStatistics: { ball_possession: 42, shots: 8, shots_on_goal: 3, corner_kicks: 3, fouls: 14 },
      goals: [
        {
          minute: 18,
          team: { name: 'Mexico' },
          scorer: { name: 'Santiago Gimenez' },
          assist: { name: 'Hirving Lozano' },
          score: { home: 1, away: 0 },
        },
        {
          minute: 51,
          team: { name: 'South Africa' },
          scorer: { name: 'Evidence Makgopa' },
          score: { home: 1, away: 1 },
        },
        {
          minute: 83,
          team: { name: 'Mexico' },
          scorer: { name: 'Edson Alvarez' },
          assist: { name: 'Luis Chavez' },
          score: { home: 2, away: 1 },
        },
      ],
      bookings: [
        { minute: 44, team: { name: 'South Africa' }, player: { name: 'Teboho Mokoena' }, card: 'YELLOW' },
      ],
      substitutions: [
        {
          minute: 67,
          team: { name: 'Mexico' },
          playerOut: { name: 'Hirving Lozano' },
          playerIn: { name: 'Uriel Antuna' },
        },
      ],
      penalties: [],
      score: { halfTime: { home: 1, away: 0 } },
    },
    events: [],
  },
  {
    id: 'mock-live-usa-par',
    round: 'Matchday 1',
    date: '2026-06-12',
    time: '6:00 PM PDT',
    kickoffAt: '2026-06-13T01:00:00Z',
    group: 'Group D',
    ground: 'SoFi Stadium',
    minute: 62,
    status: 'Live',
    home: team('United States', 'USA', '🇺🇸'),
    away: team('Paraguay', 'PAR', '🇵🇾'),
    score: { home: 1, away: 1 },
    details: {
      homeFormation: '4-3-3',
      awayFormation: '4-2-3-1',
      homeLineup: lineup('United States'),
      awayLineup: lineup('Paraguay'),
      homeBench: [{ id: 'usa-b1', name: 'USA Substitute', position: 'Winger', shirtNumber: 20 }],
      awayBench: [{ id: 'par-b1', name: 'Paraguay Substitute', position: 'Defender', shirtNumber: 15 }],
      homeStatistics: { ball_possession: 54, shots: 9, shots_on_goal: 4, corner_kicks: 6, saves: 2 },
      awayStatistics: { ball_possession: 46, shots: 7, shots_on_goal: 3, corner_kicks: 2, saves: 3 },
      goals: [
        { minute: 21, team: { name: 'United States' }, scorer: { name: 'Christian Pulisic' }, score: { home: 1, away: 0 } },
        { minute: 49, team: { name: 'Paraguay' }, scorer: { name: 'Miguel Almiron' }, score: { home: 1, away: 1 } },
      ],
      bookings: [{ minute: 37, team: { name: 'Paraguay' }, player: { name: 'Gustavo Gomez' }, card: 'YELLOW' }],
      substitutions: [],
      penalties: [],
      score: { halfTime: { home: 1, away: 0 } },
    },
    events: [],
  },
  {
    id: 'mock-can-bih',
    round: 'Matchday 1',
    date: '2026-06-12',
    time: '12:00 PM PDT',
    kickoffAt: '2026-06-12T19:00:00Z',
    group: 'Group B',
    ground: 'BC Place',
    minute: null,
    status: 'Scheduled',
    home: team('Canada', 'CAN', '🇨🇦'),
    away: team('Bosnia-Herzegovina', 'BIH', '🇧🇦'),
    score: { home: null, away: null },
    details: {},
    events: [],
  },
  {
    id: 'mock-kor-cze',
    round: 'Matchday 1',
    date: '2026-06-12',
    time: '7:00 PM PDT',
    kickoffAt: '2026-06-13T02:00:00Z',
    group: 'Group A',
    ground: 'Lumen Field',
    minute: null,
    status: 'Scheduled',
    home: team('South Korea', 'KOR', '🇰🇷'),
    away: team('Czechia', 'CZE', '🇨🇿'),
    score: { home: null, away: null },
    details: {},
    events: [],
  },
  {
    id: 'mock-jpn-gha',
    round: 'Matchday 1',
    date: '2026-06-13',
    time: '1:00 PM PDT',
    kickoffAt: '2026-06-13T20:00:00Z',
    group: 'Group C',
    ground: 'Levi\'s Stadium',
    minute: null,
    status: 'Scheduled',
    home: team('Japan', 'JPN', '🇯🇵'),
    away: team('Ghana', 'GHA', '🇬🇭'),
    score: { home: null, away: null },
    details: {},
    events: [],
  },
  {
    id: 'mock-arg-nzl',
    round: 'Matchday 1',
    date: '2026-06-13',
    time: '5:00 PM PDT',
    kickoffAt: '2026-06-14T00:00:00Z',
    group: 'Group E',
    ground: 'AT&T Stadium',
    minute: null,
    status: 'Scheduled',
    home: team('Argentina', 'ARG', '🇦🇷'),
    away: team('New Zealand', 'NZL', '🇳🇿'),
    score: { home: null, away: null },
    details: {},
    events: [],
  },
]

export const mockNews = [
  {
    id: 'mock-news-1',
    headline: 'Opening week matchups bring a coast-to-coast tournament buzz',
    timestamp: '14 min ago',
    image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80',
    category: 'Tournament',
    source: 'WCFans',
    url: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026',
  },
  {
    id: 'mock-news-2',
    headline: 'Fan rituals are already taking shape before the first whistle',
    timestamp: '46 min ago',
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=900&q=80',
    category: 'Supporters',
    source: 'WCFans',
    url: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026',
  },
  {
    id: 'mock-news-3',
    headline: 'Group stage travel notes for fans following multiple teams',
    timestamp: '2 hrs ago',
    image: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=900&q=80',
    category: 'Host Cities',
    source: 'WCFans',
    url: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026',
  },
  {
    id: 'mock-news-4',
    headline: 'Young forwards could define the first round of fixtures',
    timestamp: '3 hrs ago',
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=80',
    category: 'Analysis',
    source: 'WCFans',
    url: 'https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026',
  },
]

export const mockHaircutTracker = [
  { id: 'ARG', team: 'Argentina', flag: '🇦🇷', group: 'E', winsInARow: 5, canCutHair: true },
  { id: 'USA', team: 'United States', flag: '🇺🇸', group: 'D', winsInARow: 4, canCutHair: false },
  { id: 'MEX', team: 'Mexico', flag: '🇲🇽', group: 'A', winsInARow: 3, canCutHair: false },
  { id: 'CAN', team: 'Canada', flag: '🇨🇦', group: 'B', winsInARow: 2, canCutHair: false },
  { id: 'JPN', team: 'Japan', flag: '🇯🇵', group: 'C', winsInARow: 1, canCutHair: false },
]

export const mockStandings = [
  { group_name: 'Group A', team_id: 1, team_name: 'Mexico', team_logo: 'https://flagcdn.com/mx.svg', rank: 1, points: 3, goals_diff: 1, all_played: 1, all_win: 1, all_draw: 0, all_lose: 0 },
  { group_name: 'Group A', team_id: 2, team_name: 'South Africa', team_logo: 'https://flagcdn.com/za.svg', rank: 2, points: 0, goals_diff: -1, all_played: 1, all_win: 0, all_draw: 0, all_lose: 1 },
  { group_name: 'Group B', team_id: 3, team_name: 'Canada', team_logo: 'https://flagcdn.com/ca.svg', rank: 1, points: 0, goals_diff: 0, all_played: 0, all_win: 0, all_draw: 0, all_lose: 0 },
  { group_name: 'Group B', team_id: 4, team_name: 'Bosnia-Herzegovina', team_logo: 'https://flagcdn.com/ba.svg', rank: 2, points: 0, goals_diff: 0, all_played: 0, all_win: 0, all_draw: 0, all_lose: 0 },
  { group_name: 'Group D', team_id: 5, team_name: 'United States', team_logo: 'https://flagcdn.com/us.svg', rank: 1, points: 1, goals_diff: 0, all_played: 1, all_win: 0, all_draw: 1, all_lose: 0 },
  { group_name: 'Group D', team_id: 6, team_name: 'Paraguay', team_logo: 'https://flagcdn.com/py.svg', rank: 2, points: 1, goals_diff: 0, all_played: 1, all_win: 0, all_draw: 1, all_lose: 0 },
]

export const mockDashboardData = {
  matches: mockMatches,
  news: mockNews,
  haircutTracker: mockHaircutTracker,
  standings: mockStandings,
}
